### ISSUE TITLE
0.9.0 doesn't build with boost-1.75

### ISSUE THREAD

**Issue by g1itch** [peercoin/peercoin#558]
Hello!

Can you please backport 23b252dd to release-0.9? Without it your latest release (0.9.0) doesn't build with boost-1.75:

```
validation.cpp: In constructor ‘ConnectTrace::ConnectTrace(CTxMemPool&)’:
validation.cpp:2115:94: error: ‘_1’ was not declared in this scope
 2115 | yRemoved.connect(boost::bind(&ConnectTrace::NotifyEntryRemoved, this, _1, _2));
      |                                                                       ^~

validation.cpp:2115:94: note: suggested alternatives:
In file included from /usr/include/boost/mpl/aux_/include_preprocessed.hpp:37,
                 from /usr/include/boost/mpl/placeholders.hpp:43,
                 from /usr/include/boost/iterator/iterator_categories.hpp:16,
                 from /usr/include/boost/iterator/iterator_facade.hpp:13,
                 from /usr/include/boost/filesystem/path.hpp:29,
                 from /usr/include/boost/filesystem.hpp:16,
                 from ./fs.h:11,
                 from ./validation.h:15,
                 from validation.cpp:6:
/usr/include/boost/mpl/aux_/preprocessed/gcc/placeholders.hpp:29:16: note:   ‘mpl_::_1’
   29 | typedef arg<1> _1;
      |                ^~
In file included from /usr/include/boost/system/detail/error_category.hpp:17,
                 from /usr/include/boost/system/detail/error_code.hpp:13,
                 from /usr/include/boost/system/error_code.hpp:13,
                 from /usr/include/boost/filesystem/path_traits.hpp:22,
                 from /usr/include/boost/filesystem/path.hpp:26,
                 from /usr/include/boost/filesystem.hpp:16,
                 from ./fs.h:11,
                 from ./validation.h:15,
                 from validation.cpp:6:
/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include/g++-v9/functional:211:34: note:   ‘std::placeholders::_1’
  211 |     extern const _Placeholder<1> _1;
      |                                  ^~
In file included from /usr/include/boost/mpl/aux_/include_preprocessed.hpp:37,
                 from /usr/include/boost/mpl/placeholders.hpp:43,
                 from /usr/include/boost/iterator/iterator_categories.hpp:16,
                 from /usr/include/boost/iterator/iterator_facade.hpp:13,
                 from /usr/include/boost/filesystem/path.hpp:29,
                 from /usr/include/boost/filesystem.hpp:16,
                 from ./fs.h:11,
                 from ./validation.h:15,
                 from validation.cpp:6:
/usr/include/boost/mpl/aux_/preprocessed/gcc/placeholders.hpp:29:16: note:   ‘mpl_::_1’
   29 | typedef arg<1> _1;
      |                ^~
In file included from /usr/include/boost/bind/bind.hpp:2335,
                 from /usr/include/boost/signals2/slot.hpp:15,
                 from /usr/include/boost/signals2/connection.hpp:25,
                 from /usr/include/boost/signals2/signal.hpp:22,
                 from ./util.h:31,
                 from ./dbwrapper.h:12,
                 from ./txdb.h:10,
                 from validation.cpp:31:
/usr/include/boost/bind/placeholders.hpp:58:38: note:   ‘boost::placeholders::_1’
   58 | BOOST_STATIC_CONSTEXPR boost::arg<1> _1;
      |                                      ^~
In file included from /usr/include/boost/mpl/aux_/include_preprocessed.hpp:37,
                 from /usr/include/boost/mpl/placeholders.hpp:43,
                 from /usr/include/boost/iterator/iterator_categories.hpp:16,
                 from /usr/include/boost/iterator/iterator_facade.hpp:13,
                 from /usr/include/boost/filesystem/path.hpp:29,
                 from /usr/include/boost/filesystem.hpp:16,
                 from ./fs.h:11,
                 from ./validation.h:15,
                 from validation.cpp:6:
/usr/include/boost/mpl/aux_/preprocessed/gcc/placeholders.hpp:29:16: note:   ‘mpl_::_1’
   29 | typedef arg<1> _1;
      |                ^~
validation.cpp:2115:98: error: ‘_2’ was not declared in this scope
 2115 | ect(boost::bind(&ConnectTrace::NotifyEntryRemoved, this, _1, _2));
      |                                                              ^~

validation.cpp:2115:98: note: suggested alternatives:
In file included from /usr/include/boost/mpl/aux_/include_preprocessed.hpp:37,
                 from /usr/include/boost/mpl/placeholders.hpp:43,
                 from /usr/include/boost/iterator/iterator_categories.hpp:16,
                 from /usr/include/boost/iterator/iterator_facade.hpp:13,
                 from /usr/include/boost/filesystem/path.hpp:29,
                 from /usr/include/boost/filesystem.hpp:16,
                 from ./fs.h:11,
                 from ./validation.h:15,
                 from validation.cpp:6:
/usr/include/boost/mpl/aux_/preprocessed/gcc/placeholders.hpp:42:16: note:   ‘mpl_::_2’
   42 | typedef arg<2> _2;
      |                ^~
In file included from /usr/include/boost/system/detail/error_category.hpp:17,
                 from /usr/include/boost/system/detail/error_code.hpp:13,
                 from /usr/include/boost/system/error_code.hpp:13,
                 from /usr/include/boost/filesystem/path_traits.hpp:22,
                 from /usr/include/boost/filesystem/path.hpp:26,
                 from /usr/include/boost/filesystem.hpp:16,
                 from ./fs.h:11,
                 from ./validation.h:15,
                 from validation.cpp:6:
/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include/g++-v9/functional:212:34: note:   ‘std::placeholders::_2’
  212 |     extern const _Placeholder<2> _2;
      |                                  ^~
In file included from /usr/include/boost/mpl/aux_/include_preprocessed.hpp:37,
                 from /usr/include/boost/mpl/placeholders.hpp:43,
                 from /usr/include/boost/iterator/iterator_categories.hpp:16,
                 from /usr/include/boost/iterator/iterator_facade.hpp:13,
                 from /usr/include/boost/filesystem/path.hpp:29,
                 from /usr/include/boost/filesystem.hpp:16,
                 from ./fs.h:11,
                 from ./validation.h:15,
                 from validation.cpp:6:
/usr/include/boost/mpl/aux_/preprocessed/gcc/placeholders.hpp:42:16: note:   ‘mpl_::_2’
   42 | typedef arg<2> _2;
      |                ^~
In file included from /usr/include/boost/bind/bind.hpp:2335,
                 from /usr/include/boost/signals2/slot.hpp:15,
                 from /usr/include/boost/signals2/connection.hpp:25,
                 from /usr/include/boost/signals2/signal.hpp:22,
                 from ./util.h:31,
                 from ./dbwrapper.h:12,
                 from ./txdb.h:10,
                 from validation.cpp:31:
/usr/include/boost/bind/placeholders.hpp:59:38: note:   ‘boost::placeholders::_2’
   59 | BOOST_STATIC_CONSTEXPR boost::arg<2> _2;
      |                                      ^~
In file included from /usr/include/boost/mpl/aux_/include_preprocessed.hpp:37,
                 from /usr/include/boost/mpl/placeholders.hpp:43,
                 from /usr/include/boost/iterator/iterator_categories.hpp:16,
                 from /usr/include/boost/iterator/iterator_facade.hpp:13,
                 from /usr/include/boost/filesystem/path.hpp:29,
                 from /usr/include/boost/filesystem.hpp:16,
                 from ./fs.h:11,
                 from ./validation.h:15,
                 from validation.cpp:6:
/usr/include/boost/mpl/aux_/preprocessed/gcc/placeholders.hpp:42:16: note:   ‘mpl_::_2’
   42 | typedef arg<2> _2;
      |                ^~
validation.cpp: In destructor ‘ConnectTrace::~ConnectTrace()’:
validation.cpp:2119:97: error: ‘_1’ was not declared in this scope
 2119 | moved.disconnect(boost::bind(&ConnectTrace::NotifyEntryRemoved, this, _1, _2));
      |                                                                       ^~

validation.cpp:2119:97: note: suggested alternatives:
In file included from /usr/include/boost/mpl/aux_/include_preprocessed.hpp:37,
                 from /usr/include/boost/mpl/placeholders.hpp:43,
                 from /usr/include/boost/iterator/iterator_categories.hpp:16,
                 from /usr/include/boost/iterator/iterator_facade.hpp:13,
                 from /usr/include/boost/filesystem/path.hpp:29,
                 from /usr/include/boost/filesystem.hpp:16,
                 from ./fs.h:11,
                 from ./validation.h:15,
                 from validation.cpp:6:
/usr/include/boost/mpl/aux_/preprocessed/gcc/placeholders.hpp:29:16: note:   ‘mpl_::_1’
   29 | typedef arg<1> _1;
      |                ^~
In file included from /usr/include/boost/system/detail/error_category.hpp:17,
                 from /usr/include/boost/system/detail/error_code.hpp:13,
                 from /usr/include/boost/system/error_code.hpp:13,
                 from /usr/include/boost/filesystem/path_traits.hpp:22,
                 from /usr/include/boost/filesystem/path.hpp:26,
                 from /usr/include/boost/filesystem.hpp:16,
                 from ./fs.h:11,
                 from ./validation.h:15,
                 from validation.cpp:6:
/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include/g++-v9/functional:211:34: note:   ‘std::placeholders::_1’
  211 |     extern const _Placeholder<1> _1;
      |                                  ^~
In file included from /usr/include/boost/mpl/aux_/include_preprocessed.hpp:37,
                 from /usr/include/boost/mpl/placeholders.hpp:43,
                 from /usr/include/boost/iterator/iterator_categories.hpp:16,
                 from /usr/include/boost/iterator/iterator_facade.hpp:13,
                 from /usr/include/boost/filesystem/path.hpp:29,
                 from /usr/include/boost/filesystem.hpp:16,
                 from ./fs.h:11,
                 from ./validation.h:15,
                 from validation.cpp:6:
/usr/include/boost/mpl/aux_/preprocessed/gcc/placeholders.hpp:29:16: note:   ‘mpl_::_1’
   29 | typedef arg<1> _1;
      |                ^~
In file included from /usr/include/boost/bind/bind.hpp:2335,
                 from /usr/include/boost/signals2/slot.hpp:15,
                 from /usr/include/boost/signals2/connection.hpp:25,
                 from /usr/include/boost/signals2/signal.hpp:22,
                 from ./util.h:31,
                 from ./dbwrapper.h:12,
                 from ./txdb.h:10,
                 from validation.cpp:31:
/usr/include/boost/bind/placeholders.hpp:58:38: note:   ‘boost::placeholders::_1’
   58 | BOOST_STATIC_CONSTEXPR boost::arg<1> _1;
      |                                      ^~
In file included from /usr/include/boost/mpl/aux_/include_preprocessed.hpp:37,
                 from /usr/include/boost/mpl/placeholders.hpp:43,
                 from /usr/include/boost/iterator/iterator_categories.hpp:16,
                 from /usr/include/boost/iterator/iterator_facade.hpp:13,
                 from /usr/include/boost/filesystem/path.hpp:29,
                 from /usr/include/boost/filesystem.hpp:16,
                 from ./fs.h:11,
                 from ./validation.h:15,
                 from validation.cpp:6:
/usr/include/boost/mpl/aux_/preprocessed/gcc/placeholders.hpp:29:16: note:   ‘mpl_::_1’
   29 | typedef arg<1> _1;
      |                ^~
validation.cpp:2119:101: error: ‘_2’ was not declared in this scope
 2119 | ect(boost::bind(&ConnectTrace::NotifyEntryRemoved, this, _1, _2));
      |                                                              ^~

validation.cpp:2119:101: note: suggested alternatives:
In file included from /usr/include/boost/mpl/aux_/include_preprocessed.hpp:37,
                 from /usr/include/boost/mpl/placeholders.hpp:43,
                 from /usr/include/boost/iterator/iterator_categories.hpp:16,
                 from /usr/include/boost/iterator/iterator_facade.hpp:13,
                 from /usr/include/boost/filesystem/path.hpp:29,
                 from /usr/include/boost/filesystem.hpp:16,
                 from ./fs.h:11,
                 from ./validation.h:15,
                 from validation.cpp:6:
/usr/include/boost/mpl/aux_/preprocessed/gcc/placeholders.hpp:42:16: note:   ‘mpl_::_2’
   42 | typedef arg<2> _2;
      |                ^~
In file included from /usr/include/boost/system/detail/error_category.hpp:17,
                 from /usr/include/boost/system/detail/error_code.hpp:13,
                 from /usr/include/boost/system/error_code.hpp:13,
                 from /usr/include/boost/filesystem/path_traits.hpp:22,
                 from /usr/include/boost/filesystem/path.hpp:26,
                 from /usr/include/boost/filesystem.hpp:16,
                 from ./fs.h:11,
                 from ./validation.h:15,
                 from validation.cpp:6:
/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include/g++-v9/functional:212:34: note:   ‘std::placeholders::_2’
  212 |     extern const _Placeholder<2> _2;
      |                                  ^~
In file included from /usr/include/boost/mpl/aux_/include_preprocessed.hpp:37,
                 from /usr/include/boost/mpl/placeholders.hpp:43,
                 from /usr/include/boost/iterator/iterator_categories.hpp:16,
                 from /usr/include/boost/iterator/iterator_facade.hpp:13,
                 from /usr/include/boost/filesystem/path.hpp:29,
                 from /usr/include/boost/filesystem.hpp:16,
                 from ./fs.h:11,
                 from ./validation.h:15,
                 from validation.cpp:6:
/usr/include/boost/mpl/aux_/preprocessed/gcc/placeholders.hpp:42:16: note:   ‘mpl_::_2’
   42 | typedef arg<2> _2;
      |                ^~
In file included from /usr/include/boost/bind/bind.hpp:2335,
                 from /usr/include/boost/signals2/slot.hpp:15,
                 from /usr/include/boost/signals2/connection.hpp:25,
                 from /usr/include/boost/signals2/signal.hpp:22,
                 from ./util.h:31,
                 from ./dbwrapper.h:12,
                 from ./txdb.h:10,
                 from validation.cpp:31:
/usr/include/boost/bind/placeholders.hpp:59:38: note:   ‘boost::placeholders::_2’
   59 | BOOST_STATIC_CONSTEXPR boost::arg<2> _2;
      |                                      ^~
In file included from /usr/include/boost/mpl/aux_/include_preprocessed.hpp:37,
                 from /usr/include/boost/mpl/placeholders.hpp:43,
                 from /usr/include/boost/iterator/iterator_categories.hpp:16,
                 from /usr/include/boost/iterator/iterator_facade.hpp:13,
                 from /usr/include/boost/filesystem/path.hpp:29,
                 from /usr/include/boost/filesystem.hpp:16,
                 from ./fs.h:11,
                 from ./validation.h:15,
                 from validation.cpp:6:
/usr/include/boost/mpl/aux_/preprocessed/gcc/placeholders.hpp:42:16: note:   ‘mpl_::_2’
   42 | typedef arg<2> _2;
      |                ^~
make[2]: *** [Makefile:6529: libbitcoin_server_a-validation.o] Error 1
```

**Comment by sandakersmann** [comment]
@peerchemist @backpacker69 Would be great to get this fixed as soon as possible :)

**Comment by peerchemist** [comment]
This can probably be closed now as v0.10.0 is about to be released.
